# Iris Dataset Operations (Complete Notebook)
Subsetting, Merging, Sorting, Transposing, Melting, and Casting

In [1]:
# 1. Import Library
import pandas as pd

## 2. Load Dataset (Fix: No Header Issue)

In [2]:
# Load dataset without header
df = pd.read_csv("../DSBDALExam DataSets/Iris/Iris.csv", header=None)

# Assign proper column names
df.columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
# Basic Info
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

## g. Create data subsets for different species

In [4]:
setosa_df = df[df['Species'] == 'Iris-setosa']
versicolor_df = df[df['Species'] == 'Iris-versicolor']

setosa_df.head(), versicolor_df.head()

(   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
 0            5.1           3.5            1.4           0.2  Iris-setosa
 1            4.9           3.0            1.4           0.2  Iris-setosa
 2            4.7           3.2            1.3           0.2  Iris-setosa
 3            4.6           3.1            1.5           0.2  Iris-setosa
 4            5.0           3.6            1.4           0.2  Iris-setosa,
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
 50            7.0           3.2            4.7           1.4  Iris-versicolor
 51            6.4           3.2            4.5           1.5  Iris-versicolor
 52            6.9           3.1            4.9           1.5  Iris-versicolor
 53            5.5           2.3            4.0           1.3  Iris-versicolor
 54            6.5           2.8            4.6           1.5  Iris-versicolor)

## h. Merge two subsets

In [5]:
merged_df = pd.concat([setosa_df, versicolor_df])
merged_df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

## i. Sort Data by Petal Length

In [6]:
sorted_df = df.sort_values(by='PetalLengthCm', ascending=False)
sorted_df.head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
118            7.7           2.6            6.9           2.3  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
105            7.6           3.0            6.6           2.1  Iris-virginica
131            7.9           3.8            6.4           2.0  Iris-virginica

## j. Transposing Data

In [7]:
transpose_df = df.T
transpose_df.head()

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

## k. Melting Data to long format

In [8]:
melted_df = pd.melt(
    df,
    id_vars=['Species'],
    value_vars=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'],
    var_name='Feature',
    value_name='Value'
)

melted_df.head()

       Species        Feature  Value
0  Iris-setosa  SepalLengthCm    5.1
1  Iris-setosa  SepalLengthCm    4.9
2  Iris-setosa  SepalLengthCm    4.7
3  Iris-setosa  SepalLengthCm    4.6
4  Iris-setosa  SepalLengthCm    5.0

## l. Casting data to wide format

In [9]:
wide_df = melted_df.pivot_table(
    index='Species',
    columns='Feature',
    values='Value',
)

wide_df

Feature          PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm
Species
Iris-setosa              1.464         0.244          5.006         3.418
Iris-versicolor          4.260         1.326          5.936         2.770
Iris-virginica           5.552         2.026          6.588         2.974

## Conclusion
- Subsetting done using condition
- Merging done using concat
- Sorting based on Petal Length
- Data reshaped using transpose, melt, and pivot

Perform the following operations using Python on the Iris data sets
g. Create data subsetsfor differentspecies
h. Merge two subsets
i. Sort Data Petal Length
j. Transposing Data
k. Melting Data to long format
l. Casting data to wide format