# Movie Dataset Analysis
Operations: Subset, Merge, Sort, Transpose, Melt, Pivot

In [1]:
# 1. Import Library
import pandas as pd

In [2]:
# 2. Load Dataset
df = pd.read_csv("../DSBDALExam DataSets/Movie/movies_metadata.csv", low_memory=False)
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [3]:
# Basic Info
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

## m. Subsets for different languages

In [4]:
english_df = df[df['original_language'] == 'en']
french_df = df[df['original_language'] == 'fr']

english_df.head(), french_df.head()

(   adult                              belongs_to_collection    budget  \
 0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
 1  False                                                NaN  65000000
 2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
 3  False                                                NaN  16000000
 4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0

                                               genres  \
 0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
 1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
 2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
 3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
 4                     [{'id': 35, 'name': 'Comedy'}]

                                homepage     id    imdb_id original_language  \
 0  http://toystory.disney.com/toy-story    862  tt0114709                en
 1                                   NaN   8844  tt0113497                en
 2                                   NaN  15602  tt0113228                en
 3                                   NaN  31357  tt0114885                en
 4                                   NaN  11862  tt0113041                en

                 original_title  \
 0                    Toy Story
 1                      Jumanji
 2             Grumpier Old Men
 3            Waiting to Exhale
 4  Father of the Bride Part II

                                             overview  ... release_date  \
 0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
 1  When siblings Judy and Peter discover an encha...  ...   1995-12-15
 2  A family wedding reignites the ancient feud be...  ...   1995-12-22
 3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
 4  Just when George Banks has recovered from his ...  ...   1995-02-10

        revenue runtime                                   spoken_languages  \
 0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
 1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
 2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
 3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
 4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

      status                                            tagline  \
 0  Released                                                NaN
 1  Released          Roll the dice and unleash the excitement!
 2  Released  Still Yelling. Still Fighting. Still Ready for...
 3  Released  Friends are the people who let you be yourself...
 4  Released  Just When His World Is Back To Normal... He's ...

                          title  video vote_average vote_count
 0                    Toy Story  False          7.7     5415.0
 1                      Jumanji  False          6.9     2413.0
 2             Grumpier Old Men  False          6.5       92.0
 3            Waiting to Exhale  False          6.1       34.0
 4  Father of the Bride Part II  False          5.7      173.0

 [5 rows x 24 columns],
     adult belongs_to_collection    budget  \
 28  False                   NaN  18000000
 32  False                   NaN         0
 58  False                   NaN         0
 67  False                   NaN         0
 72  False                   NaN         0

                                                genres homepage     id  \
 28  [{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...      NaN    902
 32  [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...      NaN  78802
 58  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...      NaN  99040
 67  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...      NaN   4482
 72  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...      NaN  48750

       imdb_id original_language                    original_title  \
 28  tt0112682                fr        La Cité des Enfants Perdus
 32  tt0114952                fr  Guillaumet, les ailes du courage
 58  tt0112714                fr                  Le confessionnal
 67  tt0113149                fr                      Gazon maudit
 72  tt0113828                fr                    Les misérables

                                              overview  ... release_date  \
 28  A scientist in a surrealist society kidnaps ch...  ...   1995-05-16
 32                                                NaN  ...   1996-09-18
 58  The year is 1952, in Quebec City. Rachel (16),...  ...   1995-09-29
 67  After learning of her husband's infidelities, ...  ...   1995-02-08
 72  In France during World War II, a poor and illi...  ...   1995-03-22

       revenue runtime                                   spoken_languages  \
 28  1738611.0   108.0  [{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}, {'i...
 32        0.0    50.0           [{'iso_639_1': 'en', 'name': 'English'}]
 58        0.0   100.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
 67        0.0    95.0  [{'iso_639_1': 'fr', 'name': 'Français'}, {'is...
 72        0.0   175.0          [{'iso_639_1': 'fr', 'name': 'Français'}]

       status                                            tagline  \
 28  Released          Where happily ever after is just a dream.
 32  Released                                                NaN
 58  Released                                                NaN
 67  Released                                                NaN
 72  Released  In a time of chaos, in a world of change, he w...

                         title  video vote_average vote_count
 28  The City of Lost Children  False          7.6      308.0
 32           Wings of Courage  False          6.8        4.0
 58           The Confessional  False          6.5        2.0
 67               French Twist  False          6.0       43.0
 72             Les Miserables  False          6.6        8.0

 [5 rows x 24 columns])

## n. Merge subsets

In [5]:
merged_df = pd.concat([english_df, french_df])
merged_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

## o. Sort by customer ratings

In [6]:
sorted_df = df.sort_values(by='vote_average', ascending=False)
sorted_df[['title', 'vote_average']].head()

                                       title  vote_average
31082                              Time Pass          10.0
45371  LEGO DC Super Hero Girls: Brain Drain          10.0
21798                      Stealing a Nation          10.0
23851                     Slaying the Badger          10.0
35999                     The Lion of Thebes          10.0

## p. Transpose

In [7]:
transpose_df = df.T
transpose_df.head()

,0,1,2,3,4,5,6,7,8,9,...,45456,45457,45458,45459,45460,45461,45462,45463,45464,45465
adult,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
belongs_to_collection,"{'id': 10194, 'name': 'Toy Story Collection', ...",NaN,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",NaN,"{'id': 96871, 'name': 'Father of the Bride Col...",NaN,NaN,NaN,NaN,"{'id': 645, 'name': 'James Bond Collection', '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
budget,30000000,65000000,0,16000000,0,60000000,58000000,0,35000000,58000000,...,0,0,0,0,0,0,0,0,0,0
genres,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 35, 'name': 'Comedy'}]","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",...,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...","[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...","[{'id': 27, 'name': 'Horror'}]","[{'id': 878, 'name': 'Science Fiction'}]","[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'id': 18, 'name': 'Drama'}]","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",[],[]
homepage,http://toystory.disney.com/toy-story,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mgm.com/view/movie/757/Goldeneye/,...,NaN,NaN,NaN,NaN,NaN,http://www.imdb.com/title/tt6209470/,NaN,NaN,NaN,NaN

## q. Melt to long format

In [8]:
df['vote_average'] = pd.to_numeric(df['vote_average'], errors='coerce')
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')
melted_df = pd.melt(
    df,
    id_vars=['original_language'],
    value_vars=['vote_average', 'popularity'],
    var_name='Metric',
    value_name='Value'
)

melted_df.head()

  original_language        Metric  Value
0                en  vote_average    7.7
1                en  vote_average    6.9
2                en  vote_average    6.5
3                en  vote_average    6.1
4                en  vote_average    5.7

## r. Pivot to wide format

In [9]:
df['vote_average'] = pd.to_numeric(df['vote_average'], errors='coerce')
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')
wide_df = melted_df.pivot_table(
    index='original_language',
    columns='Metric',
    values='Value'
)

wide_df

Metric             popularity  vote_average
original_language
ab                   1.182567      5.000000
af                   3.291494      6.200000
am                   0.332316      7.450000
ar                   1.002735      6.817949
ay                   0.640637      6.000000
...                       ...           ...
vi                   0.966772      5.880000
wo                   0.137103      6.520000
xx                   1.461472      5.854545
zh                   2.314828      6.366993
zu                   1.678469      8.300000

[89 rows x 2 columns]

## Conclusion
- Subsets created using language filter
- Merged using concat
- Sorted by ratings
- Data reshaped using transpose, melt, pivot

Perform the following operations using Python on Movie data sets
m. Create data subsetsfor different languages(Original Language).
n. Merge two subsets
o. Sort Data using customer ratings.
p. Transposing Data
q. Melting Data to long format
r. Casting data to wide format