# Forest Fires Dataset Operations
Handling dataset without column names

In [1]:
import pandas as pd

## Load Dataset (No Header)

In [2]:
df = pd.read_csv("../DSBDALExam DataSets/forestfires/forestfires.csv")

df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

## a. Create Subsets

In [3]:
# Objective: Classify forest fire severity based on area
print("Objective: Classify area into NotAffected, PartiallyAffected, MostlyAffected")

def classify_area(x):
    if x == 0:
        return "NotAffected"
    elif x <= 50:
        return "PartiallyAffected"
    else:
        return "MostlyAffected"

df['area_class'] = df['area'].apply(classify_area)

subset1 = df[df['area_class'] == "NotAffected"]
subset2 = df[df['area_class'] == "PartiallyAffected"]
subset3 = df[df['area_class'] == "MostlyAffected"]

print(len(subset1), len(subset2), len(subset3))

Objective: Classify area into NotAffected, PartiallyAffected, MostlyAffected
247 246 24

## b. Merge Two Subsets

In [4]:
# Objective: Combine partially and mostly affected areas
print("Objective: Merge PartiallyAffected and MostlyAffected")

merged = pd.concat([subset2, subset3])
merged.shape

Objective: Merge PartiallyAffected and MostlyAffected

(270, 14)

## c. Sort Data

In [5]:
# Objective: Sort by temperature, wind and area
print("Objective: Sort dataset based on temp, wind and area")

sorted_df = df.sort_values(by=['temp','wind','area'])
sorted_df[['temp','wind','area']].head()

Objective: Sort dataset based on temp, wind and area

     temp  wind  area
280   2.2   4.9  9.27
282   4.2   4.0  0.00
465   4.6   0.9  6.84
463   4.6   6.3  5.39
279   4.6   8.5  9.77

## d. Transpose Data

In [6]:
# Objective: Swap rows and columns
print("Objective: Transpose dataset")

df.head().T

Objective: Transpose dataset

                      0            1            2            3            4
X                     7            7            7            8            8
Y                     5            4            4            6            6
month               mar          oct          oct          mar          mar
day                 fri          tue          sat          fri          sun
FFMC               86.2         90.6         90.6         91.7         89.3
DMC                26.2         35.4         43.7         33.3         51.3
DC                 94.3        669.1        686.9         77.5        102.2
ISI                 5.1          6.7          6.7          9.0          9.6
temp                8.2         18.0         14.6          8.3         11.4
RH                   51           33           33           97           99
wind                6.7          0.9          1.3          4.0          1.8
rain                0.0          0.0          0.0          0.2          0.0
area                0.0          0.0          0.0          0.0          0.0
area_class  NotAffected  NotAffected  NotAffected  NotAffected  NotAffected

## e. Melt Data

In [7]:
# Objective: Convert wide format to long format
print("Objective: Melt data to long format")

melted = pd.melt(df,
                 id_vars=['month','day'],
                 value_vars=['temp','RH','wind'],
                 var_name='Parameter',
                 value_name='Value')

melted.head()

Objective: Melt data to long format

  month  day Parameter  Value
0   mar  fri      temp    8.2
1   oct  tue      temp   18.0
2   oct  sat      temp   14.6
3   mar  fri      temp    8.3
4   mar  sun      temp   11.4

## f. Cast to Wide Format

In [8]:
# Objective: Convert long format back to wide format
print("Objective: Convert melted data back to wide format")

wide = melted.pivot_table(index=['month','day'],
                          columns='Parameter',
                          values='Value')

wide.head()

Objective: Convert melted data back to wide format

Parameter    RH  temp      wind
month day
apr   fri  20.0  16.7  3.100000
      mon  64.0  10.9  3.100000
      sat  44.0   9.3  4.500000
      sun  45.0  14.9  5.666667
      thu  54.0   5.8  5.800000